"""Generate shared definitions and browser shader assets. Use --check in CI."""

import argparse
import json
import shutil
import subprocess
from pathlib import Path

from engine.catalog import load_catalog, catalog_hash as catalog_hash
from engine.schedule import KERNEL_SPECS, MOVEMENT_SALT_COUNT, movement_schedule_for_tick
from engine.wgsl_fixer import strip_entry_points_and_bindings
from engine.version import RULES_VERSION


ROOT = Path(__file__).resolve().parent.parent


def constants(catalog: dict) -> dict[str, int]:
    result = {"SCHEMA_VERSION": catalog["schema_version"]}
    for name, field in catalog["bit_fields"].items():
        for suffix, value in (("BITS", field["bits"]), ("SHIFT", field["shift"]), ("MASK", (1 << field["bits"]) - 1)):
            result[f"{name.upper()}_{suffix}"] = value
    for name, field in catalog["structure_fields"].items():
        result[f"STRUCTURE_{name.upper()}_MASK"] = ((1 << field["bits"]) - 1) << field["shift"]
    result["STRUCTURE_COMPLETE_MASK"] = (1 << catalog["structure_fields"]["fresh"]["shift"]) - 1
    result["STRUCTURE_INTERNAL_MASK"] = (1 << max(field["shift"] + field["bits"] for field in catalog["structure_fields"].values())) - 1
    result.update({f"MAT_{m['name'].upper()}": m["id"] for m in catalog["materials"]})
    result.update({f"PHASE_{name}": value for name, value in catalog["phases"].items()})
    result.update({f"FLAG_{name}": value for name, value in catalog["flags"].items()})
    result.update({"COLD_TABLE_STRIDE": catalog["cold_stride"], "COLD_TABLE_ENTRIES": catalog["capacity"],
                   "COLD_TABLE_SIZE_BYTES": catalog["cold_stride"] * catalog["capacity"] * 4})
    result.update({f"COLD_{name.upper()}": index for index, name in enumerate(catalog["cold_fields"])})
    return result


def browser_definitions(catalog: dict, typescript: bool) -> str:
    lines = ["// Generated by python -m engine.generate; edit engine/materials.json."]
    values = constants(catalog)
    lines.append(f'export const MATERIAL_CATALOG_HASH = "{catalog_hash(catalog)}";')
    lines.append(f'export const RULES_VERSION = "{RULES_VERSION}";')
    for name, value in values.items():
        lines.append(f"export const {name} = {value};")
    lines.append("export const COLD_STRIDE = COLD_TABLE_STRIDE;")
    signature = "function freezeDefinition<T>(value: T): T {" if typescript else "function freezeDefinition(value) {"
    lines.extend([signature, "  if (value !== null && typeof value === 'object') {",
                  "    for (const child of Object.values(value)) freezeDefinition(child);",
                  "    Object.freeze(value);", "  }", "  return value;", "}"])
    records = sorted(catalog["materials"], key=lambda r: r["id"])
    tables = {
        "MAT": {r["name"].upper(): r["id"] for r in records},
        "PHASE": catalog["phases"], "FLAG": catalog["flags"],
        "MATERIAL_NAMES": {r["id"]: r["name"] for r in records},
        "MATERIAL_VISUALS": {r["id"]: r["color"] for r in records},
        "MAT_PHASE": {r["id"]: r["properties"]["default_phase"] for r in records},
        "MAT_THERMAL": {r["id"]: r["default_thermal"] for r in records},
        "COLD_ROWS": [[r["id"], *[r["properties"][f] for f in catalog["cold_fields"]]] for r in records],
    }
    for name, data in tables.items():
        annotation = ""
        suffix = ""
        if typescript:
            if name in ("MATERIAL_NAMES", "MATERIAL_VISUALS"):
                annotation = ": Record<number, string>"
            elif name in ("MAT_PHASE", "MAT_THERMAL"):
                annotation = ": Record<number, number>"
            else:
                suffix = " as const"
        lines.append(f"export const {name}{annotation} = freezeDefinition({json.dumps(data, indent=2)}{suffix});")
    lines.append(f"export const DEFAULT_CATALOG = freezeDefinition({json.dumps(catalog, indent=2)});")
    lines.extend(["export function buildColdTable() {", "  const buffer = new Uint32Array(COLD_TABLE_ENTRIES * COLD_STRIDE);",
                  "  for (const [id, ...props] of COLD_ROWS) buffer.set(props, id * COLD_STRIDE);",
                  "  return buffer;", "}", ""])
    return "\n".join(lines)


def generated_outputs(root: Path = ROOT) -> dict[Path, str]:
    catalog = load_catalog(root / "engine/materials.json")
    values = constants(catalog)
    python = '"""Generated by python -m engine.generate; edit engine/materials.json."""\n\n'
    python += "\n".join(f"{key} = {value}" for key, value in values.items()) + "\n"
    wgsl = "// Generated by python -m engine.generate; edit engine/materials.json.\n"
    wgsl += "\n".join(f"const {key}: u32 = {value}u;" for key, value in values.items() if not key.startswith("COLD_"))
    wgsl += "\n\nstruct VoxelState {\n    material: u32,\n    thermal: u32,\n    kinetic_x: i32,\n    kinetic_y: i32,\n    phase: u32,\n    flags: u32,\n}\n\noverride GRID_WIDTH: u32 = 256u;\noverride GRID_HEIGHT: u32 = 256u;\n"
    outputs = {
        root / "engine/_generated_schema.py": python,
        root / "engine/generated/materials.ts": browser_definitions(catalog, True),
        root / "web/materials.generated.js": browser_definitions(catalog, False),
        root / "engine/shaders/bitmask_defs.wgsl": wgsl,
        root / "web/shaders/bitmask_defs.wgsl": wgsl,
    }
    for name in {"phase_1a_winner.wgsl", *(spec.source_file for spec in KERNEL_SPECS)}:
        outputs[root / "engine/kernels" / name] = (root / "locked" / name).read_text(encoding="utf-8")
    node = shutil.which("node")
    if node is None:
        raise RuntimeError("Node.js and the root npm dependencies are required to generate browser runtime assets")
    transpile = "const ts=require('typescript'); let s=''; process.stdin.setEncoding('utf8'); process.stdin.on('data',c=>s+=c); process.stdin.on('end',()=>process.stdout.write(ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText));"
    for name in ("validation", "registry", "thermal", "structure", "contracts"):
        source = (root / "engine" / f"{name}.ts").read_text(encoding="utf-8")
        compiled = subprocess.run([node, "-e", transpile], input=source, capture_output=True, text=True,
                                  encoding="utf-8", cwd=ROOT, timeout=30, check=True).stdout
        compiled = compiled.replace("'./generated/materials.js'", "'./materials.generated.js'")
        for dependency in ("validation", "registry", "thermal", "structure"):
            compiled = compiled.replace(f"'./{dependency}.js'", f"'./{dependency}.generated.js'")
        outputs[root / "web" / f"{name}.generated.js"] = "// Generated by python -m engine.generate.\n" + compiled
    from dataclasses import asdict
    schedules = [movement_schedule_for_tick(tick) for tick in range(MOVEMENT_SALT_COUNT)]
    schedule_source = "// Generated by python -m engine.generate; edit engine/schedule.py.\n"
    schedule_source += f"export const KERNEL_SPECS = {json.dumps([asdict(spec) for spec in KERNEL_SPECS], indent=2)};\n"
    schedule_source += f"const SCHEDULES = {json.dumps(schedules)};\n"
    body = f"  return SCHEDULES[tick % {MOVEMENT_SALT_COUNT}];\n}}\n"
    outputs[root / "engine/generated/schedule.ts"] = schedule_source + "export function movementScheduleForTick(tick: number): string[] {\n" + body
    outputs[root / "web/schedule.generated.js"] = schedule_source + "export function movementScheduleForTick(tick) {\n" + body
    sources = {"BITMASK_DEFS": wgsl, "LOCKED_1A": strip_entry_points_and_bindings((root / "locked/phase_1a_winner.wgsl").read_text(encoding="utf-8"))}
    for name in ("state_io", "enthalpy_law"):
        source = (root / "engine/shaders" / f"{name}.wgsl").read_text(encoding="utf-8")
        outputs[root / "web/shaders" / f"{name}.wgsl"] = source
        sources[name.upper()] = source
    outputs[root / "web/shaders/locked_1a.wgsl"] = sources["LOCKED_1A"]
    kernels = {"gravity": "phase_2b_winner.wgsl", "diagonal": "phase_2b_diagonal_winner.wgsl",
               "liquid": "phase_2b_liquid_winner.wgsl", "gas_buoyancy": "phase_2b_gas_buoyancy_winner.wgsl",
               "gas_spread": "phase_2b_gas_spread_winner.wgsl", "thermal": "phase_2a_winner.wgsl",
               "phase": "phase_2c_winner.wgsl", "combustion": "phase_2d_winner.wgsl",
               "structure": "phase_2e_structure.wgsl", "normalize": "phase_2e_normalize.wgsl"}
    for name, filename in kernels.items():
        source = (root / "locked" / filename).read_text(encoding="utf-8")
        outputs[root / "web/shaders" / f"{name}.wgsl"] = source
        sources[name.upper() + "_SHADER"] = source
    common = sources["BITMASK_DEFS"] + "\n\n" + sources["LOCKED_1A"] + "\n\n" + sources["STATE_IO"] + "\n" + sources["ENTHALPY_LAW"] + "\n"
    runtime_kernels = {filename: (root / "locked" / filename).read_text(encoding="utf-8") for filename in kernels.values()}
    outputs[root / "engine/generated/shaders.ts"] = (
        "// Generated by python -m engine.generate; edit the authoritative WGSL files.\n"
        + f"export const COMMON_SHADER = {json.dumps(common)};\n"
        + f"export const KERNEL_SOURCES: Readonly<Record<string, string>> = Object.freeze({json.dumps(runtime_kernels, indent=2)});\n")
    palette = "fn material_color(mat_id: u32) -> vec3<f32> {\n    switch mat_id {\n"
    for record in catalog["materials"]:
        rgb = [int(record["color"][offset:offset + 2], 16) / 255 for offset in (1, 3, 5)]
        palette += f"        case {record['id']}u: {{ return vec3<f32>({', '.join(f'{channel:.8f}' for channel in rgb)}); }}\n"
    palette += "        default: { return vec3<f32>(1.0, 0.0, 1.0); }\n    }\n}\n"
    sources["RENDER_SHADER"] = palette + (root / "web/render.wgsl").read_text(encoding="utf-8")
    outputs[root / "web/shaders.js"] = "// Generated by python -m engine.generate.\n" + "\n".join(
        f"export const {name} = {json.dumps(source)};" for name, source in sources.items()) + "\n"
    return outputs


def check_generated(root: Path = ROOT) -> list[str]:
    return [str(path.relative_to(root)) for path, expected in generated_outputs(root).items()
            if not path.exists() or path.read_text(encoding="utf-8") != expected]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        stale = check_generated()
        for path in stale:
            print(f"SS001 generated asset drift: {path}")
        return int(bool(stale))
    for path, source in generated_outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
