export const KEY_BINDINGS = {
  left: 'A',
  right: 'D',
  up: 'W',
  jumpAlt: 'SPACE',
  down: 'S',
  dash: 'SHIFT',
  block: 'K',
  attack: 'J',
  special: 'U',
  shield: 'K',
  grab: 'L',
  basic: 'J',
  special1: 'U',
  special2: 'I',
  special3: 'O',
  restart: 'R',
  debug: 'BACKTICK',
} as const;
