// Generated by python -m engine.generate; edit engine/materials.json.
const SCHEMA_VERSION: u32 = 3u;
const MATERIAL_BITS: u32 = 8u;
const MATERIAL_SHIFT: u32 = 0u;
const MATERIAL_MASK: u32 = 255u;
const THERMAL_BITS: u32 = 8u;
const THERMAL_SHIFT: u32 = 8u;
const THERMAL_MASK: u32 = 255u;
const KINETIC_X_BITS: u32 = 4u;
const KINETIC_X_SHIFT: u32 = 16u;
const KINETIC_X_MASK: u32 = 15u;
const KINETIC_Y_BITS: u32 = 4u;
const KINETIC_Y_SHIFT: u32 = 20u;
const KINETIC_Y_MASK: u32 = 15u;
const PHASE_BITS: u32 = 4u;
const PHASE_SHIFT: u32 = 24u;
const PHASE_MASK: u32 = 15u;
const FLAGS_BITS: u32 = 4u;
const FLAGS_SHIFT: u32 = 28u;
const FLAGS_MASK: u32 = 15u;
const STRUCTURE_INTEGRITY_MASK: u32 = 255u;
const STRUCTURE_BOND_LEFT_MASK: u32 = 256u;
const STRUCTURE_BOND_RIGHT_MASK: u32 = 512u;
const STRUCTURE_BOND_UP_MASK: u32 = 1024u;
const STRUCTURE_BOND_DOWN_MASK: u32 = 2048u;
const STRUCTURE_ANCHOR_MASK: u32 = 4096u;
const STRUCTURE_FRESH_MASK: u32 = 8192u;
const STRUCTURE_COMPLETE_MASK: u32 = 8191u;
const STRUCTURE_INTERNAL_MASK: u32 = 16383u;
const MAT_AIR: u32 = 0u;
const MAT_STONE: u32 = 1u;
const MAT_WATER: u32 = 2u;
const MAT_SAND: u32 = 3u;
const MAT_FIRE: u32 = 4u;
const MAT_METAL: u32 = 5u;
const MAT_OIL: u32 = 6u;
const MAT_WOOD: u32 = 7u;
const MAT_ICE: u32 = 8u;
const MAT_STEAM: u32 = 9u;
const MAT_LAVA: u32 = 10u;
const MAT_GLASS: u32 = 11u;
const MAT_PLAYER: u32 = 12u;
const MAT_ASH: u32 = 13u;
const MAT_SMOKE: u32 = 14u;
const MAT_OIL_VAPOR: u32 = 15u;
const MAT_MOLTEN_METAL: u32 = 16u;
const MAT_MOLTEN_GLASS: u32 = 17u;
const PHASE_SOLID: u32 = 0u;
const PHASE_POWDER: u32 = 1u;
const PHASE_LIQUID: u32 = 2u;
const PHASE_VISCOUS: u32 = 3u;
const PHASE_GAS: u32 = 4u;
const PHASE_PLASMA: u32 = 5u;
const PHASE_FROZEN: u32 = 6u;
const PHASE_MOLTEN: u32 = 7u;
const PHASE_BURNING: u32 = 8u;
const PHASE_CONDENSING: u32 = 9u;
const PHASE_EVAPORATING: u32 = 10u;
const PHASE_SUBLIMATING: u32 = 11u;
const FLAG_BURNING: u32 = 1u;
const FLAG_CONDUCTING: u32 = 2u;
const FLAG_PRESSURIZED: u32 = 4u;
const FLAG_PLAYER_OWNED: u32 = 8u;

struct VoxelState {
    material: u32,
    thermal: u32,
    kinetic_x: i32,
    kinetic_y: i32,
    phase: u32,
    flags: u32,
}

override GRID_WIDTH: u32 = 256u;
override GRID_HEIGHT: u32 = 256u;
